### ISSUE TITLE
Better block manager API

### ISSUE THREAD

**Issue by artggd** [umanit/block-bundle#5]
ATM, it is required for the end-user to call `parent::buildForm($builder, $options);` in a block manager's `buildForm` method otherwise the `position` field is never added.

This is quite a bad DX and architecture as such call can easily be forgotten. We should wrap up the block managers to dynamically add the position field.

**Comment by artggd** [comment]
Using form extension rather than form type would be a clean option.

**Comment by DjLeChuck** [comment]
I have tried to use FormTypeExtension, but it's not possible because the extended form type list cannot be dynamic (or maybe with a compiler pass, but I don't think).

Another possibility is to add an global event on all form (with a form extension on the Symfony FormType to catch all) but I don't find it clean. I have no idea for the moment instead of calling the parent. 😕

**Comment by DjLeChuck** [comment]
Oh, it works with parenting.

When declaring the block form type, adding this do the job:

```php
    public function getParent(): string
    {
        return BlockType::class;
    }
```

**Comment by DjLeChuck** [comment]
Made with a double class to facilitate the integration by the developer: ad0d1190859f66eac47940501b586aeef80a10ce
